### ISSUE TITLE
Server side rendering & tooling

### ISSUE THREAD

**Issue by ofahchouch-gh** [dewarian/progressive-web-apps-2021#1]
Nice, je bent aan de slag gegaan met tooling. Je gebruikt verschillende tools en schrijft ook je eigen build scripts. 

Alleen werken de build scripts nog niet helemaal nadat er meer dan 1x wordt gebuild? Er wordt niks naar mijn dist folder geschreven als ik npm run build draai ;o?

npm start hoort eigenlijk ook de app in de dist te starten en niet je app in je root (dev omgeving)?

Als tip voor server side rendering zou ik je routing, applicatie logica en domein logica apart schrijven. Ik doe dat met routes, controllers en services.

**Comment by bommezijn** [comment]
Feedback verwerkt en toegepast. 

Op dit moment als de build script word opgeroepen zal het de dist folder compleet overschrijven waardoor het lijkt dat er niks gebeurt.
Indien de routing complexer gaat worden zal ik deze ook opsplitsen.
