### ISSUE TITLE
Code review week 1

### ISSUE THREAD

**Issue by RobinFrugte97** [dewarian/progressive-web-apps-2021#2]
Yo Nathan!

Lekker bezig met je tooling man! Goeie script chain ook al! Package.json goed ingevuld.

Prettige commit messages ook, duidelijk omschreven en consistent, nice! Lekker begin van je readme! Kijk of je nog een stukje kan vertellen over de scripts die je gebruikt en wat ze ongeveer doen. Vertel over je chain! Schrijf misschien een stukje over je packages, met bronverwijzingen naar de docs.

Je bent al bezig met je templates opsplitsen, nice. Nu je data nog verwerken in je templates.

Succes!

**Comment by bommezijn** [comment]
Dankjewel voor de feedback. Ik zal dit verwerken in de applicatie en documentatie!

**Comment by bommezijn** [comment]
Documentatie en templating toegepast.
